### ISSUE TITLE
Registrierung in Frontend implementieren

### ISSUE THREAD

**Issue by Veenc0** [The-Older-Ones/frontend-project#15]

**Comment by KFDugong** [comment]
Hello! Kann jemand bitte reinschreiben, inwiefern die Registrierung implementiert werden soll? Was für Akzeptanzkriterien wollen wir für diese Aufgabe festlegen?

**Comment by Yejay** [comment]
> Hello! Kann jemand bitte reinschreiben, inwiefern die Registrierung implementiert werden soll? Was für Akzeptanzkriterien wollen wir für diese Aufgabe festlegen?

Das müssten wir mal mit @Veenc0 und @Deltainu klären, um herauszufinden, wie der Endpoint aufgebaut ist.
Mögliche Akzeptanzkriterien wären erstmal sowas wie:
- [ ] Registrierungsformular anzeigen
- [ ] Pflichtfelder überprüfen
- [ ] Passwortanforderungen überprüfen
- [ ] Passwortbestätigung
- [ ] Eindeutige Benutzernamen
- [ ] Fehlerbehandlung
- [ ] Erfolgreiche Registrierung
