### ISSUE TITLE
Login in Frontend implementieren

### ISSUE THREAD

**Issue by Veenc0** [The-Older-Ones/frontend-project#16]

**Comment by KFDugong** [comment]
Wo ist der Unterschied zu frontend-project#15?

**Comment by Yejay** [comment]
> Wo ist der Unterschied zu frontend-project#15?

frontend-project#15 ist die reine Implementierung der Registrierung, hier soll nur das Login umgesetzt werden, dementsprechend muss frontend-project#15 als erstes umgesetzt werden.
