### ISSUE TITLE
Design a layout for the landing page

### ISSUE THREAD

**Issue by KFDugong** [The-Older-Ones/frontend-project#6]
Design the layout of the landing page according to the wireframes in Figma. There is no need for any details yet. Work with Material UI's Paper components and give it a distinct color. 

Task to get to know Material UI's framework and the layout structure.

**Comment by Yejay** [comment]
Ich schließe das Ticket, da es ein Duplikat davon gibt und ich die Ticket-ID davon schon für Git genutzt habe.
